// <auto-generated />
using System;
using ERPFacturacao.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERPFacturacao.Migrations
{
    [DbContext(typeof(EFContext))]
    [Migration("20230528144319_inicial2")]
    partial class inicial2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ERPFacturacao.Model.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataActualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_actualizacao");

                    b.Property<DateTime>("DataAnulacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_anulacao");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_registo");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("utilizadores_cargos_id");

                    b.Property<string>("_Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("cargo");

                    b.HasKey("Id");

                    b.ToTable("cargos");
                });

            modelBuilder.Entity("ERPFacturacao.Model.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataActualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_actualizacao");

                    b.Property<DateTime>("DataAnulacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_anulacao");

                    b.Property<DateTime>("DataRegisto")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_registo");

                    b.Property<string>("Sigla")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int")
                        .HasColumnName("utilizadores_sectores_id");

                    b.Property<string>("_Sector")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("sector");

                    b.HasKey("Id");

                    b.ToTable("sectores");
                });

            modelBuilder.Entity("ERPFacturacao.Model.Utilizador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSu")
                        .HasColumnType("bit");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Senha")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("_Utilizador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("utilizador");

                    b.HasKey("Id");

                    b.ToTable("utilizadores");
                });
#pragma warning restore 612, 618
        }
    }
}
